server:
  port: 8086

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/kss_db_product_seata
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mkxiaoer
  application:
    name: seata-product
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-product

seata:
  service:
    vgroup-mapping:
      seata-product: default
    grouplist:
      default: 127.0.0.1:8091