server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kss_db_order_seata
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mkxiaoer
  application:
    name: seata-order
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-order

seata:
  service:
    vgroup-mapping:
      seata-order: default
    grouplist:
      default: 127.0.0.1:8091