spring:
  cloud:
    nacos:
      discovery:
        server-addr: 121.40.151.95:8848
  rabbitmq:
    host: 121.40.151.95.190
    port: 5672
    username: admin
    password: admin
    virtual-host: /
  data:
    mongodb:
      uri: mongodb://root:zhengge@localhost:27017
      database: traveldb
  servlet:
    multipart:
      # 文件上传大小限制。超过该值直接报错
      max-file-size: 20MB
      # 文件最大请求限制，用于批量上传
      max-request-size: 20MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/travel-client-parent?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 30
      minimum-idle: 10
      read-only: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

logging:
  level:
    root: info


# MinIO 配置
minio:
  endpoint: http://121.40.151.95:9000      # MinIO服务地址
  fileHost: http://121.40.151.95:9000      # 文件地址host
  bucketName: travelapp                       # 存储桶bucket名称
  accessKey: root                         # 用户名
  secretKey: 12345678                     # 密码
  imgSize: 20                           # 图片大小限制，单位：m
  fileSize: 20                          # 文件大小限制，单位：m




########################微信小程序 - 微信支付参数#######################################
#微信商户号
wechat:
  mchId: 1615158475
  #商家API证书序列号
  mchSerialNo: 61B27028E8DDBA019C55791F9D12F52DEF84A862
  #微信小程序APPID
  appId: wx2130f87b8f96cff7
  #回调报文解密V3密钥key
  v3Key: 0139a6d9e93fb88d3d68e0a8a1b06bd6
  #微信获取平台证书列表地址
  certificates:
    url: https://api.mch.weixin.qq.com/v3/certificates
  #微信统一下单Navtive的API地址，用于二维码支付
  unifiedOrder:
    #微信统一下单JSAPI的API地址，用于微信小程序
    url: https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi
  #异步接收微信支付结果通知的回调地址
  callback: http://www.kuangstudy.com/api/pay/wechat-pay/notifyUrl
  #商户证书私钥路径
  key:
    path: /www/paykey/apiclient_key.pem
########################微信支付参数#######################################